// <auto-generated />
namespace ZD.InfoManager.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_user_AvatarPath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_user_AvatarPath));
        
        string IMigrationMetadata.Id
        {
            get { return "201712120740177_add_user_AvatarPath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
