// <auto-generated />
namespace ZD.InfoManager.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addSecurityInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSecurityInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201712251305510_addSecurityInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
